import Section from "@/components/Section";
import Stat from "@/components/Stat";
import AskBox from "@/components/AskBox";
import {
  generateRecommendations,
  forecastAll,
  pricingModel,
  launchTargets,
  Priority,
} from "@/lib/ai/predict";
import { categories } from "@/lib/data/products";

const STRATEGY_SUGGESTIONS = [
  "What should I do next?",
  "Launch order matrix",
  "Show me 90 day forecast",
  "Which formulations are declining?",
  "Top distributors in Maharashtra",
  "Pricing for Glow Serum",
  "Which state has the highest demand for Premium Milk Soap?",
  "Composite demand ranking across India",
];

const priorityBar = (p: Priority) => {
  const map: Record<Priority, string> = {
    Critical: "bg-ink text-paper",
    High: "bg-ink text-paper",
    Medium: "bg-paper text-ink",
    Low: "bg-paper text-ink",
  };
  return map[p];
};

export default function Page() {
  const recs = generateRecommendations();
  const lt = launchTargets().slice(0, 8);
  const pm = pricingModel();
  const fc = forecastAll();

  const critical = recs.filter((r) => r.priority === "Critical").length;
  const high = recs.filter((r) => r.priority === "High").length;
  const medium = recs.filter((r) => r.priority === "Medium").length;

  // Forecast aggregation: highest 90 day growth by state.
  const topGrowth = [...fc]
    .filter((f) => f.day90 > f.base)
    .sort((a, b) => (b.day90 - b.base) - (a.day90 - a.base))
    .slice(0, 8);

  return (
    <div>
      <AskBox
        title="Ask The Strategy Engine"
        subtitle="Ask any strategic question. The engine answers from the same data that drives the recommendations below."
        suggestions={STRATEGY_SUGGESTIONS}
        showHistory={false}
      />

      <Section
        title="AI Strategy Engine"
        subtitle="Recommendations are generated by combining the Goldbees product catalog, regional demand index, distributor fit scoring and live trend signals. Each card explains what to do, why the data supports it, and why the action is useful."
      >
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <Stat label="Recommendations" value={recs.length} sub="generated from current data" />
          <Stat label="Critical" value={critical} sub="act this week" />
          <Stat label="High Priority" value={high} sub="act inside 30 days" />
          <Stat label="Medium" value={medium} sub="plan inside 90 days" />
        </div>
      </Section>

      <Section
        title="Strategic Recommendations"
        subtitle="Ranked by priority. Confidence reflects how strongly the underlying data supports the recommendation."
      >
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {recs.map((r, i) => (
            <div key={r.id} className="surface surface-hover flex flex-col">
              <div className="border-b border-ink px-4 py-2.5 flex items-center justify-between gap-3">
                <div className="flex items-center gap-2.5">
                  <span className="num text-ink/40 text-xs">{String(i + 1).padStart(2, "0")}</span>
                  <span className="eyebrow text-ink/55">{r.kind}</span>
                </div>
                <div className={"text-[10px] uppercase tracking-widest px-2.5 py-1 border border-ink " + priorityBar(r.priority)}>
                  {r.priority}
                </div>
              </div>
              <div className="p-5 flex-1 flex flex-col gap-4 text-sm">
                <div className="font-display font-semibold text-lg leading-snug">{r.title}</div>
                <div>
                  <div className="eyebrow text-ink/45 mb-1.5">Action</div>
                  <p className="text-ink/85 leading-relaxed">{r.action}</p>
                </div>
                <div>
                  <div className="eyebrow text-ink/45 mb-1.5">Why The Data Supports It</div>
                  <ul className="space-y-1.5">
                    {r.reasoning.map((line, j) => (
                      <li key={j} className="flex gap-2.5 text-ink/85">
                        <span className="mt-1.5 h-1 w-1 rounded-full bg-ink shrink-0" />
                        <span className="leading-relaxed">{line}</span>
                      </li>
                    ))}
                  </ul>
                </div>
                <div>
                  <div className="eyebrow text-ink/45 mb-1.5">Expected Outcome</div>
                  <p className="text-ink/85 leading-relaxed">{r.expectedOutcome}</p>
                </div>
                <div className="border-t border-ink/15 pt-3 mt-auto">
                  <div className="eyebrow text-ink/45 mb-1.5">Why This Is Useful</div>
                  <p className="text-xs text-ink/70 leading-relaxed">{r.whyUseful}</p>
                </div>
                <div className="border-t border-ink/15 pt-3">
                  <div className="flex items-center justify-between eyebrow text-ink/55 mb-2">
                    <span>Confidence</span>
                    <span className="num text-ink">{r.confidence}%</span>
                  </div>
                  <div className="h-1.5 w-full bg-ink/10">
                    <div className="h-1.5 bg-ink" style={{ width: `${r.confidence}%` }} />
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </Section>

      <Section
        title="Launch Priority Matrix"
        subtitle="Top product x region combinations to launch in order. Score = demand index weighted by city tier."
      >
        <div className="overflow-x-auto">
        <table className="w-full text-sm min-w-[720px]">
          <thead>
            <tr className="border-b-2 border-black">
              <th className="text-left py-2 uppercase tracking-widest text-[10px]">Rank</th>
              <th className="text-left py-2 uppercase tracking-widest text-[10px]">Region</th>
              <th className="text-left py-2 uppercase tracking-widest text-[10px]">Category</th>
              <th className="text-right py-2 uppercase tracking-widest text-[10px]">Score</th>
              <th className="text-left py-2 uppercase tracking-widest text-[10px]">Distributors Matched</th>
              <th className="text-left py-2 uppercase tracking-widest text-[10px]">Anchor Partner</th>
            </tr>
          </thead>
          <tbody>
            {lt.map((row, i) => (
              <tr key={`${row.state.code}-${row.category}`} className="border-b border-black">
                <td className="py-2 font-mono">{String(i + 1).padStart(2, "0")}</td>
                <td className="py-2">{row.state.name}, {row.state.topCity}</td>
                <td className="py-2">{row.category}</td>
                <td className="py-2 font-mono text-right">{row.score}</td>
                <td className="py-2 font-mono">{row.distributorCount}</td>
                <td className="py-2 text-xs">{row.topDistributor ? row.topDistributor.name : "Build from scratch"}</td>
              </tr>
            ))}
          </tbody>
        </table>
        </div>
      </Section>

      <Section
        title="90 Day Demand Forecast"
        subtitle="Per state x category projection. Inputs: current demand index, related trend signal direction and magnitude, city tier weight."
      >
        <div className="overflow-x-auto">
        <table className="w-full text-sm min-w-[720px]">
          <thead>
            <tr className="border-b-2 border-black">
              <th className="text-left py-2 uppercase tracking-widest text-[10px]">State</th>
              <th className="text-left py-2 uppercase tracking-widest text-[10px]">Category</th>
              <th className="text-right py-2 uppercase tracking-widest text-[10px]">Base</th>
              <th className="text-right py-2 uppercase tracking-widest text-[10px]">D+30</th>
              <th className="text-right py-2 uppercase tracking-widest text-[10px]">D+60</th>
              <th className="text-right py-2 uppercase tracking-widest text-[10px]">D+90</th>
              <th className="text-right py-2 uppercase tracking-widest text-[10px]">Δ vs Base</th>
            </tr>
          </thead>
          <tbody>
            {topGrowth.map((f) => (
              <tr key={`${f.stateCode}-${f.category}`} className="border-b border-black">
                <td className="py-2">{f.state}</td>
                <td className="py-2">{f.category}</td>
                <td className="py-2 font-mono text-right">{f.base}</td>
                <td className="py-2 font-mono text-right">{f.day30}</td>
                <td className="py-2 font-mono text-right">{f.day60}</td>
                <td className="py-2 font-mono text-right">{f.day90}</td>
                <td className="py-2 font-mono text-right font-semibold">+{f.day90 - f.base}</td>
              </tr>
            ))}
          </tbody>
        </table>
        </div>
        <p className="text-[10px] uppercase tracking-widest mt-3">
          This is a directional forecast for a prototype. Production builds add seasonality, festival calendar, weather and live POS data.
        </p>
      </Section>

      <Section
        title="Pricing Recommendations"
        subtitle="Suggested D2C and marketplace MRP, distributor price and retailer margin per SKU. Based on landed cost from costing notes."
      >
        <div className="overflow-x-auto">
        <table className="w-full text-sm min-w-[720px]">
          <thead>
            <tr className="border-b-2 border-black">
              <th className="text-left py-2 uppercase tracking-widest text-[10px]">Product</th>
              <th className="text-left py-2 uppercase tracking-widest text-[10px]">Size</th>
              <th className="text-right py-2 uppercase tracking-widest text-[10px]">Landed</th>
              <th className="text-right py-2 uppercase tracking-widest text-[10px]">Distributor Price</th>
              <th className="text-right py-2 uppercase tracking-widest text-[10px]">Retailer Margin</th>
              <th className="text-right py-2 uppercase tracking-widest text-[10px]">Marketplace MRP</th>
              <th className="text-right py-2 uppercase tracking-widest text-[10px]">D2C MRP</th>
              <th className="text-right py-2 uppercase tracking-widest text-[10px]">D2C Gross %</th>
            </tr>
          </thead>
          <tbody>
            {pm.map((m) => (
              <tr key={m.product.id} className="border-b border-black">
                <td className="py-2 pr-2">
                  <div className="font-semibold">{m.product.name}</div>
                  <div className="text-[10px] uppercase tracking-widest">{m.product.category}</div>
                </td>
                <td className="py-2 font-mono">{m.product.size}</td>
                <td className="py-2 font-mono text-right">₹{m.landed}</td>
                <td className="py-2 font-mono text-right">₹{m.distributorPrice}</td>
                <td className="py-2 font-mono text-right">₹{m.retailerMargin}</td>
                <td className="py-2 font-mono text-right">₹{m.marketplaceMrp}</td>
                <td className="py-2 font-mono text-right">₹{m.d2cMrp}</td>
                <td className="py-2 font-mono text-right">{m.d2cGrossMargin}%</td>
              </tr>
            ))}
          </tbody>
        </table>
        </div>
      </Section>

      <Section
        title="How The AI Layer Works"
        subtitle="A transparent view of the inputs, scoring and outputs the engine uses."
      >
        <div className="grid md:grid-cols-3 gap-6 text-sm leading-relaxed">
          <div className="surface surface-hover p-5">
            <div className="text-[10px] uppercase tracking-widest mb-2">Inputs</div>
            <ul className="list-disc pl-5">
              <li>Product catalog with landed cost</li>
              <li>Regional demand index per category</li>
              <li>Distributor fit score and compliance</li>
              <li>Trend signals across Amazon, Flipkart, Quick Commerce, IndiaMART</li>
              <li>City tier weighting</li>
            </ul>
          </div>
          <div className="surface surface-hover p-5">
            <div className="text-[10px] uppercase tracking-widest mb-2">Scoring Math</div>
            <ul className="list-disc pl-5">
              <li>Launch score = demand x tier weight</li>
              <li>Forecast = base x (1 + trend% x horizon x tier)</li>
              <li>Distributor priority = fit score x category overlap</li>
              <li>Pricing = landed x channel multiplier</li>
              <li>Confidence = supporting signal density</li>
            </ul>
          </div>
          <div className="surface surface-hover p-5">
            <div className="text-[10px] uppercase tracking-widest mb-2">Outputs</div>
            <ul className="list-disc pl-5">
              <li>Ranked recommendations with reasoning</li>
              <li>Launch priority matrix</li>
              <li>30 / 60 / 90 day demand forecast</li>
              <li>Per SKU pricing model</li>
              <li>Distributor activation sequence</li>
            </ul>
          </div>
        </div>
      </Section>
    </div>
  );
}
